-- Generated from joblake.skills/catalogue.json. Version 2026-10-02.1.
CREATE OR REPLACE FUNCTION core.skill_key(value text) RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path='' AS $$
 SELECT CASE lower(regexp_replace(btrim(normalize(value,NFC)), '[[:space:]]+', ' ', 'g'))
 WHEN '.net' THEN 'dotnet'
 WHEN '.net core' THEN 'dotnet-core'
 WHEN '3d studio max' THEN '3dsmax'
 WHEN '3ds max' THEN '3dsmax'
 WHEN 'active directory' THEN 'active-directory'
 WHEN 'adobe after effects' THEN 'after-effects'
 WHEN 'adobe illustrator' THEN 'illustrator'
 WHEN 'adobe indesign' THEN 'indesign'
 WHEN 'adobe photoshop' THEN 'photoshop'
 WHEN 'adobe premiere pro' THEN 'premiere-pro'
 WHEN 'after effects' THEN 'after-effects'
 WHEN 'agile' THEN 'agile'
 WHEN 'ai' THEN 'ai'
 WHEN 'airflow' THEN 'airflow'
 WHEN 'amazon web services' THEN 'aws'
 WHEN 'android' THEN 'android'
 WHEN 'angular' THEN 'angular'
 WHEN 'ansible' THEN 'ansible'
 WHEN 'apache airflow' THEN 'airflow'
 WHEN 'apache http server' THEN 'apache'
 WHEN 'apache kafka' THEN 'kafka'
 WHEN 'apache spark' THEN 'spark'
 WHEN 'api' THEN 'api'
 WHEN 'api testing' THEN 'api-testing'
 WHEN 'argo cd' THEN 'argocd'
 WHEN 'argocd' THEN 'argocd'
 WHEN 'artificial intelligence' THEN 'ai'
 WHEN 'asp.net' THEN 'aspnet'
 WHEN 'asp.net core' THEN 'aspnet-core'
 WHEN 'autocad' THEN 'autocad'
 WHEN 'aws' THEN 'aws'
 WHEN 'azure' THEN 'azure'
 WHEN 'azure devops' THEN 'azure-devops'
 WHEN 'b2b sales' THEN 'b2b-sales'
 WHEN 'bash' THEN 'bash'
 WHEN 'big data' THEN 'big-data'
 WHEN 'bigquery' THEN 'bigquery'
 WHEN 'blender' THEN 'blender'
 WHEN 'bootstrap' THEN 'bootstrap'
 WHEN 'bpmn' THEN 'bpmn'
 WHEN 'brd' THEN 'brd'
 WHEN 'business analysis' THEN 'business-analysis'
 WHEN 'bán hàng' THEN 'sales'
 WHEN 'c' THEN 'c'
 WHEN 'c#' THEN 'csharp'
 WHEN 'c++' THEN 'cplusplus'
 WHEN 'canva' THEN 'canva'
 WHEN 'capcut' THEN 'capcut'
 WHEN 'chatgpt' THEN 'chatgpt'
 WHEN 'chinese' THEN 'chinese'
 WHEN 'chăm sóc khách hàng' THEN 'customer-service'
 WHEN 'ci/cd' THEN 'cicd'
 WHEN 'claude' THEN 'claude'
 WHEN 'confluence' THEN 'confluence'
 WHEN 'content marketing' THEN 'content-marketing'
 WHEN 'copywriting' THEN 'copywriting'
 WHEN 'cpp' THEN 'cplusplus'
 WHEN 'crm' THEN 'crm'
 WHEN 'csharp' THEN 'csharp'
 WHEN 'cskh' THEN 'customer-service'
 WHEN 'css' THEN 'css'
 WHEN 'css3' THEN 'css3'
 WHEN 'cypress' THEN 'cypress'
 WHEN 'dart' THEN 'dart'
 WHEN 'data analysis' THEN 'data-analysis'
 WHEN 'data modeling' THEN 'data-modeling'
 WHEN 'data warehouse' THEN 'data-warehouse'
 WHEN 'databricks' THEN 'databricks'
 WHEN 'dbt' THEN 'dbt'
 WHEN 'design patterns' THEN 'design-patterns'
 WHEN 'design system' THEN 'design-system'
 WHEN 'devops' THEN 'devops'
 WHEN 'devsecops' THEN 'devsecops'
 WHEN 'digital marketing' THEN 'digital-marketing'
 WHEN 'django' THEN 'django'
 WHEN 'dns' THEN 'dns'
 WHEN 'docker' THEN 'docker'
 WHEN 'dotnet' THEN 'dotnet'
 WHEN 'dotnet core' THEN 'dotnet-core'
 WHEN 'elasticsearch' THEN 'elasticsearch'
 WHEN 'english' THEN 'english'
 WHEN 'erp' THEN 'erp'
 WHEN 'etl' THEN 'etl'
 WHEN 'excel' THEN 'excel'
 WHEN 'express' THEN 'express'
 WHEN 'express.js' THEN 'express'
 WHEN 'expressjs' THEN 'express'
 WHEN 'facebook ads' THEN 'facebook-ads'
 WHEN 'fastapi' THEN 'fastapi'
 WHEN 'figma' THEN 'figma'
 WHEN 'financial analysis' THEN 'financial-analysis'
 WHEN 'firebase' THEN 'firebase'
 WHEN 'flask' THEN 'flask'
 WHEN 'flutter' THEN 'flutter'
 WHEN 'gcp' THEN 'gcp'
 WHEN 'giao tiếp' THEN 'communication'
 WHEN 'git' THEN 'git'
 WHEN 'github' THEN 'github'
 WHEN 'github actions' THEN 'github-actions'
 WHEN 'gitlab' THEN 'gitlab'
 WHEN 'gitlab ci' THEN 'gitlab-ci'
 WHEN 'go' THEN 'go'
 WHEN 'golang' THEN 'go'
 WHEN 'google ads' THEN 'google-ads'
 WHEN 'google analytics' THEN 'google-analytics'
 WHEN 'google cloud platform' THEN 'gcp'
 WHEN 'google sheets' THEN 'google-sheets'
 WHEN 'grafana' THEN 'grafana'
 WHEN 'graphql' THEN 'graphql'
 WHEN 'grpc' THEN 'grpc'
 WHEN 'hadoop' THEN 'hadoop'
 WHEN 'helm' THEN 'helm'
 WHEN 'hive' THEN 'hive'
 WHEN 'hrm' THEN 'hrm'
 WHEN 'html' THEN 'html'
 WHEN 'html5' THEN 'html5'
 WHEN 'illustrator' THEN 'illustrator'
 WHEN 'indesign' THEN 'indesign'
 WHEN 'ios' THEN 'ios'
 WHEN 'iso 27001' THEN 'iso27001'
 WHEN 'iso27001' THEN 'iso27001'
 WHEN 'japanese' THEN 'japanese'
 WHEN 'java' THEN 'java'
 WHEN 'javascript' THEN 'javascript'
 WHEN 'jenkins' THEN 'jenkins'
 WHEN 'jest' THEN 'jest'
 WHEN 'jira' THEN 'jira'
 WHEN 'jmeter' THEN 'jmeter'
 WHEN 'jquery' THEN 'jquery'
 WHEN 'js' THEN 'javascript'
 WHEN 'junit' THEN 'junit'
 WHEN 'jwt' THEN 'jwt'
 WHEN 'k8s' THEN 'kubernetes'
 WHEN 'kafka' THEN 'kafka'
 WHEN 'kotlin' THEN 'kotlin'
 WHEN 'kubernetes' THEN 'kubernetes'
 WHEN 'kế toán' THEN 'accounting'
 WHEN 'kỹ năng giao tiếp' THEN 'communication'
 WHEN 'kỹ năng làm việc nhóm' THEN 'teamwork'
 WHEN 'kỹ năng thuyết phục' THEN 'persuasion'
 WHEN 'kỹ năng thuyết trình' THEN 'presentation'
 WHEN 'kỹ năng đàm phán' THEN 'negotiation'
 WHEN 'langchain' THEN 'langchain'
 WHEN 'laravel' THEN 'laravel'
 WHEN 'large language models' THEN 'llm'
 WHEN 'linux' THEN 'linux'
 WHEN 'llm' THEN 'llm'
 WHEN 'làm việc nhóm' THEN 'teamwork'
 WHEN 'lập kế hoạch' THEN 'planning'
 WHEN 'machine learning' THEN 'machine-learning'
 WHEN 'macos' THEN 'macos'
 WHEN 'mariadb' THEN 'mariadb'
 WHEN 'matplotlib' THEN 'matplotlib'
 WHEN 'mes' THEN 'mes'
 WHEN 'microservices' THEN 'microservices'
 WHEN 'microsoft 365' THEN 'microsoft365'
 WHEN 'microsoft azure' THEN 'azure'
 WHEN 'microsoft excel' THEN 'excel'
 WHEN 'microsoft power bi' THEN 'powerbi'
 WHEN 'microsoft powerpoint' THEN 'powerpoint'
 WHEN 'microsoft sql server' THEN 'sqlserver'
 WHEN 'microsoft word' THEN 'word'
 WHEN 'mongodb' THEN 'mongodb'
 WHEN 'mssql' THEN 'sqlserver'
 WHEN 'mvc' THEN 'mvc'
 WHEN 'mysql' THEN 'mysql'
 WHEN 'nest.js' THEN 'nestjs'
 WHEN 'nestjs' THEN 'nestjs'
 WHEN 'next.js' THEN 'nextjs'
 WHEN 'nextjs' THEN 'nextjs'
 WHEN 'nginx' THEN 'nginx'
 WHEN 'node js' THEN 'nodejs'
 WHEN 'node.js' THEN 'nodejs'
 WHEN 'nodejs' THEN 'nodejs'
 WHEN 'nosql' THEN 'nosql'
 WHEN 'numpy' THEN 'numpy'
 WHEN 'oauth 2.0' THEN 'oauth2'
 WHEN 'oauth2' THEN 'oauth2'
 WHEN 'object oriented programming' THEN 'oop'
 WHEN 'odoo' THEN 'odoo'
 WHEN 'office 365' THEN 'microsoft365'
 WHEN 'oop' THEN 'oop'
 WHEN 'opensearch' THEN 'opensearch'
 WHEN 'oracle' THEN 'oracle'
 WHEN 'owasp top 10' THEN 'owasp-top10'
 WHEN 'pandas' THEN 'pandas'
 WHEN 'photoshop' THEN 'photoshop'
 WHEN 'php' THEN 'php'
 WHEN 'phân tích dữ liệu' THEN 'data-analysis'
 WHEN 'phân tích nghiệp vụ' THEN 'business-analysis'
 WHEN 'phân tích tài chính' THEN 'financial-analysis'
 WHEN 'playwright' THEN 'playwright'
 WHEN 'postgres' THEN 'postgresql'
 WHEN 'postgresql' THEN 'postgresql'
 WHEN 'postman' THEN 'postman'
 WHEN 'power automate' THEN 'power-automate'
 WHEN 'power bi' THEN 'powerbi'
 WHEN 'powerpoint' THEN 'powerpoint'
 WHEN 'powershell' THEN 'powershell'
 WHEN 'premiere' THEN 'premiere-pro'
 WHEN 'premiere pro' THEN 'premiere-pro'
 WHEN 'product management' THEN 'product-management'
 WHEN 'project management' THEN 'project-management'
 WHEN 'prometheus' THEN 'prometheus'
 WHEN 'pytest' THEN 'pytest'
 WHEN 'python' THEN 'python'
 WHEN 'pytorch' THEN 'pytorch'
 WHEN 'quản lý dự án' THEN 'project-management'
 WHEN 'quản trị mạng' THEN 'network-admin'
 WHEN 'rabbitmq' THEN 'rabbitmq'
 WHEN 'rag' THEN 'rag'
 WHEN 'rails' THEN 'rails'
 WHEN 'react' THEN 'react'
 WHEN 'react native' THEN 'react-native'
 WHEN 'react.js' THEN 'react'
 WHEN 'reactjs' THEN 'react'
 WHEN 'redis' THEN 'redis'
 WHEN 'rest api' THEN 'rest-api'
 WHEN 'restful api' THEN 'rest-api'
 WHEN 'retrieval augmented generation' THEN 'rag'
 WHEN 'revit' THEN 'revit'
 WHEN 'routing' THEN 'routing'
 WHEN 'ruby' THEN 'ruby'
 WHEN 'ruby on rails' THEN 'rails'
 WHEN 'rust' THEN 'rust'
 WHEN 'saas' THEN 'saas'
 WHEN 'sales' THEN 'sales'
 WHEN 'sales b2b' THEN 'b2b-sales'
 WHEN 'salesforce' THEN 'salesforce'
 WHEN 'sap' THEN 'sap'
 WHEN 'sap erp' THEN 'sap-erp'
 WHEN 'sass' THEN 'sass'
 WHEN 'scikit-learn' THEN 'scikit-learn'
 WHEN 'scrum' THEN 'scrum'
 WHEN 'scss' THEN 'sass'
 WHEN 'sdlc' THEN 'sdlc'
 WHEN 'selenium' THEN 'selenium'
 WHEN 'selenium webdriver' THEN 'selenium-webdriver'
 WHEN 'sem' THEN 'sem'
 WHEN 'seo' THEN 'seo'
 WHEN 'siem' THEN 'siem'
 WHEN 'sklearn' THEN 'scikit-learn'
 WHEN 'snowflake' THEN 'snowflake'
 WHEN 'solid' THEN 'solid'
 WHEN 'solidworks' THEN 'solidworks'
 WHEN 'spark' THEN 'spark'
 WHEN 'spring' THEN 'spring'
 WHEN 'spring boot' THEN 'spring-boot'
 WHEN 'spring security' THEN 'spring-security'
 WHEN 'springboot' THEN 'spring-boot'
 WHEN 'sql' THEN 'sql'
 WHEN 'sql server' THEN 'sqlserver'
 WHEN 'sqlite' THEN 'sqlite'
 WHEN 'srs' THEN 'srs'
 WHEN 'stlc' THEN 'stlc'
 WHEN 'swift' THEN 'swift'
 WHEN 'tableau' THEN 'tableau'
 WHEN 'tailwind css' THEN 'tailwind'
 WHEN 'tailwindcss' THEN 'tailwind'
 WHEN 'tcp/ip' THEN 'tcpip'
 WHEN 'tensorflow' THEN 'tensorflow'
 WHEN 'terraform' THEN 'terraform'
 WHEN 'thuyết phục' THEN 'persuasion'
 WHEN 'thuyết trình' THEN 'presentation'
 WHEN 'tin học văn phòng' THEN 'office-skills'
 WHEN 'tiếng anh' THEN 'english'
 WHEN 'tiếng nhật' THEN 'japanese'
 WHEN 'tiếng trung' THEN 'chinese'
 WHEN 'trello' THEN 'trello'
 WHEN 'ts' THEN 'typescript'
 WHEN 'typescript' THEN 'typescript'
 WHEN 'typography' THEN 'typography'
 WHEN 'uat' THEN 'uat'
 WHEN 'uml' THEN 'uml'
 WHEN 'unity' THEN 'unity'
 WHEN 'use case' THEN 'use-case'
 WHEN 'user story' THEN 'user-story'
 WHEN 'visio' THEN 'visio'
 WHEN 'vlan' THEN 'vlan'
 WHEN 'vue' THEN 'vue'
 WHEN 'vue.js' THEN 'vue'
 WHEN 'vuejs' THEN 'vue'
 WHEN 'websocket' THEN 'websocket'
 WHEN 'windows' THEN 'windows'
 WHEN 'windows server' THEN 'windows-server'
 WHEN 'wireframe' THEN 'wireframe'
 WHEN 'word' THEN 'word'
 WHEN 'đàm phán' THEN 'negotiation'
 END
$$;
CREATE OR REPLACE FUNCTION core.normalize_skills(values_ text[]) RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path='' AS $$
 SELECT coalesce(array_agg(DISTINCT key ORDER BY key), '{}'::text[])
 FROM (SELECT core.skill_key(v) key FROM unnest(values_) v) s WHERE key IS NOT NULL
$$;
CREATE OR REPLACE FUNCTION core.preferred_skills(required_ text[], preferred_ text[]) RETURNS text[]
LANGUAGE sql IMMUTABLE PARALLEL SAFE SET search_path='' AS $$
 SELECT ARRAY(SELECT k FROM unnest(core.normalize_skills(preferred_)) k
 WHERE NOT k=ANY(core.normalize_skills(required_)) ORDER BY k)
$$;
CREATE OR REPLACE VIEW core.current_job_skills WITH (security_invoker=true) AS
SELECT e.parse_result_id,
 CASE WHEN e.status='succeeded' THEN core.normalize_skills(ARRAY(SELECT jsonb_array_elements_text(CASE WHEN jsonb_typeof(e.result->'skills_required')='array' THEN e.result->'skills_required' ELSE '[]'::jsonb END))) ELSE '{}'::text[] END required_skill_keys,
 CASE WHEN e.status='succeeded' THEN core.preferred_skills(ARRAY(SELECT jsonb_array_elements_text(CASE WHEN jsonb_typeof(e.result->'skills_required')='array' THEN e.result->'skills_required' ELSE '[]'::jsonb END)),ARRAY(SELECT jsonb_array_elements_text(CASE WHEN jsonb_typeof(e.result->'skills_preferred')='array' THEN e.result->'skills_preferred' ELSE '[]'::jsonb END))) ELSE '{}'::text[] END preferred_skill_keys,
 '2026-10-02.1'::text normalization_version
FROM core.current_job_enrichments e;
