[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "joblake"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.15.0",
    "playwright==1.60.0",
    "PyYAML==6.0.3",
    "requests==2.34.2",
    "cloakbrowser[geoip]==0.4.13",
    "python-dotenv==1.2.2",
    "minio==7.2.20",
    "psycopg[binary]==3.3.4",
    "SQLAlchemy==2.0.52",
    "alembic==1.19.1",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
joblake = ["sql/*.sql"]
