"""Move crawl state into a dedicated PostgreSQL schema."""
from alembic import op

revision = "0002_crawl_state"
down_revision = "0001_parsed_jobs"
branch_labels = None
depends_on = None

SCHEMA_SQL = """
CREATE TABLE crawl_state.crawl_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'running', 'completed', 'failed',
            'blocked', 'suspicious'
        )
    ),
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    discovered_url_count BIGINT NOT NULL DEFAULT 0,
    new_url_count BIGINT NOT NULL DEFAULT 0,
    error_type TEXT,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE crawl_state.discovery_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    source TEXT NOT NULL,
    target_name TEXT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'running', 'completed', 'failed',
            'blocked', 'suspicious'
        )
    ),
    detected_last_page BIGINT,
    fetched_page_count BIGINT NOT NULL DEFAULT 0,
    discovered_url_count BIGINT NOT NULL DEFAULT 0,
    new_url_count BIGINT NOT NULL DEFAULT 0,
    duplicate_url_count BIGINT NOT NULL DEFAULT 0,
    empty_page_count BIGINT NOT NULL DEFAULT 0,
    invalid_page_count BIGINT NOT NULL DEFAULT 0,
    started_at TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ,
    error_type TEXT,
    error_message TEXT,
    FOREIGN KEY(run_id) REFERENCES crawl_state.crawl_runs(id),
    UNIQUE(run_id, target_name)
);

CREATE TABLE crawl_state.jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    url TEXT NOT NULL,
    first_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    last_seen_run_id BIGINT,
    last_target_name TEXT,
    last_listing_url TEXT,
    last_listing_page BIGINT,
    raw_status TEXT NOT NULL DEFAULT 'pending' CHECK (
        raw_status IN (
            'pending', 'fetching', 'validating',
            'uploading', 'raw_ready',
            'retryable_error', 'blocked',
            'permanent_error', 'storage_missing',
            'storage_corrupt'
        )
    ),
    fetch_attempt_count BIGINT NOT NULL DEFAULT 0,
    last_attempt_at TIMESTAMPTZ,
    next_retry_at TIMESTAMPTZ,
    last_http_status BIGINT,
    last_error_type TEXT,
    last_error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(last_seen_run_id) REFERENCES crawl_state.crawl_runs(id),
    UNIQUE(source, url)
);

CREATE TABLE crawl_state.fetch_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    job_id BIGINT NOT NULL,
    attempt_number BIGINT NOT NULL,
    status TEXT NOT NULL CHECK (
        status IN (
            'fetching', 'invalid_response',
            'fetch_error', 'blocked', 'uploading',
            'storage_error', 'success'
        )
    ),
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    requested_url TEXT NOT NULL,
    final_url TEXT,
    http_status BIGINT,
    content_type TEXT,
    content_length_bytes BIGINT,
    content_sha256 TEXT,
    validation_version TEXT,
    validation_report TEXT,
    storage_provider TEXT,
    bucket_name TEXT,
    object_key TEXT,
    object_version TEXT,
    fetched_at TIMESTAMPTZ,
    error_type TEXT,
    error_message TEXT,
    quarantine_bucket TEXT,
    quarantine_object_key TEXT,
    FOREIGN KEY(run_id) REFERENCES crawl_state.crawl_runs(id),
    FOREIGN KEY(job_id) REFERENCES crawl_state.jobs(id),
    UNIQUE(job_id, attempt_number)
);

CREATE TABLE crawl_state.raw_objects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    storage_provider TEXT NOT NULL,
    bucket_name TEXT NOT NULL,
    object_key TEXT NOT NULL,
    object_version TEXT,
    requested_url TEXT NOT NULL,
    final_url TEXT,
    http_status BIGINT NOT NULL,
    content_type TEXT,
    content_length_bytes BIGINT NOT NULL,
    content_sha256 TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    stored_at TIMESTAMPTZ NOT NULL,
    validation_version TEXT NOT NULL,
    validation_report TEXT NOT NULL,
    last_integrity_check_at TIMESTAMPTZ,
    integrity_status TEXT NOT NULL DEFAULT 'valid' CHECK (
        integrity_status IN (
            'unchecked', 'valid', 'missing',
            'size_mismatch', 'hash_mismatch'
        )
    ),
    FOREIGN KEY(job_id) REFERENCES crawl_state.jobs(id),
    UNIQUE(bucket_name, object_key)
);

CREATE TABLE crawl_state.parse_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT,
    job_id BIGINT NOT NULL,
    raw_object_id BIGINT NOT NULL,
    parser_name TEXT NOT NULL,
    parser_version TEXT NOT NULL,
    attempt_number BIGINT NOT NULL DEFAULT 1,
    status TEXT NOT NULL CHECK (
        status IN (
            'parsing', 'success', 'parse_error',
            'validation_error', 'raw_missing',
            'raw_corrupt'
        )
    ),
    started_at TIMESTAMPTZ NOT NULL,
    completed_at TIMESTAMPTZ,
    parsed_field_count BIGINT,
    missing_required_fields TEXT,
    warnings TEXT,
    output_location TEXT,
    error_type TEXT,
    error_message TEXT,
    FOREIGN KEY(run_id) REFERENCES crawl_state.crawl_runs(id),
    FOREIGN KEY(job_id) REFERENCES crawl_state.jobs(id),
    FOREIGN KEY(raw_object_id) REFERENCES crawl_state.raw_objects(id),
    UNIQUE(
        raw_object_id,
        parser_name,
        parser_version,
        attempt_number
    )
);

CREATE INDEX IF NOT EXISTS idx_jobs_queue
ON crawl_state.jobs(source, raw_status, next_retry_at);

CREATE INDEX IF NOT EXISTS idx_jobs_last_seen
ON crawl_state.jobs(source, last_seen_at);

CREATE INDEX IF NOT EXISTS idx_fetch_attempts_job
ON crawl_state.fetch_attempts(job_id, attempt_number DESC);

CREATE INDEX IF NOT EXISTS idx_fetch_attempts_run
ON crawl_state.fetch_attempts(run_id, status);

CREATE INDEX IF NOT EXISTS idx_targets_run
ON crawl_state.discovery_targets(run_id, status);

CREATE INDEX IF NOT EXISTS idx_parse_pending
ON crawl_state.parse_attempts(raw_object_id, parser_name, parser_version, status);


CREATE INDEX idx_parse_run ON crawl_state.parse_attempts(run_id, status);
CREATE INDEX idx_parse_claim ON crawl_state.parse_attempts(parser_name, parser_version, raw_object_id, status, run_id);
"""

def upgrade():
    op.execute("CREATE SCHEMA crawl_state")
    for statement in SCHEMA_SQL.split(";"):
        if statement.strip():
            op.execute(statement)

def downgrade():
    for table in ("parse_attempts", "raw_objects", "fetch_attempts", "jobs", "discovery_targets", "crawl_runs"):
        op.execute(f"DROP TABLE crawl_state.{table}")
    op.execute("DROP SCHEMA crawl_state")
