"""Track listing presence after complete discovery runs."""
from alembic import op

revision = "0003_url_cdc"
down_revision = "0002_crawl_state"
branch_labels = None
depends_on = None

SCHEMA_SQL = """
ALTER TABLE crawl_state.jobs
    ADD COLUMN listing_status TEXT NOT NULL DEFAULT 'unknown'
        CHECK (listing_status IN ('unknown', 'active', 'expired')),
    ADD COLUMN expired_at TIMESTAMPTZ,
    ADD COLUMN expired_run_id BIGINT REFERENCES crawl_state.crawl_runs(id),
    ADD COLUMN tracking_scope_hash TEXT;
ALTER TABLE crawl_state.crawl_runs
    ADD COLUMN phase TEXT CHECK (phase IN ('full', 'discovery', 'detail', 'parse')),
    ADD COLUMN scope_hash TEXT,
    ADD COLUMN expected_targets JSONB NOT NULL DEFAULT '[]',
    ADD COLUMN coverage_complete BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN cdc_status TEXT NOT NULL DEFAULT 'not_applicable'
        CHECK (cdc_status IN ('not_applicable', 'pending', 'baseline', 'applied', 'skipped')),
    ADD COLUMN cdc_reason TEXT,
    ADD COLUMN cdc_finished_at TIMESTAMPTZ,
    ADD COLUMN expired_url_count BIGINT NOT NULL DEFAULT 0,
    ADD COLUMN reappeared_url_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE crawl_state.discovery_targets
    ADD COLUMN coverage_complete BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN termination_reason TEXT;
CREATE TABLE crawl_state.cdc_sources (
    source TEXT PRIMARY KEY,
    scope_hash TEXT NOT NULL,
    last_applied_run_id BIGINT NOT NULL REFERENCES crawl_state.crawl_runs(id)
);
CREATE TABLE crawl_state.url_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES crawl_state.jobs(id),
    run_id BIGINT NOT NULL REFERENCES crawl_state.crawl_runs(id),
    event_type TEXT NOT NULL CHECK (event_type IN ('EXPIRED', 'REAPPEARED')),
    previous_status TEXT NOT NULL,
    new_status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (run_id, job_id, event_type)
);
CREATE INDEX idx_jobs_cdc ON crawl_state.jobs(source, tracking_scope_hash, listing_status, last_seen_run_id);
CREATE INDEX idx_runs_cdc ON crawl_state.crawl_runs(source, phase, id);
CREATE INDEX idx_url_events_job ON crawl_state.url_events(job_id, id);
"""


def upgrade():
    for statement in SCHEMA_SQL.split(';'):
        if statement.strip():
            op.execute(statement)


def downgrade():
    op.execute("DROP TABLE crawl_state.url_events")
    op.execute("DROP TABLE crawl_state.cdc_sources")
    op.execute("DROP INDEX crawl_state.idx_jobs_cdc")
    op.execute("DROP INDEX crawl_state.idx_runs_cdc")
    op.execute("ALTER TABLE crawl_state.jobs DROP COLUMN listing_status, DROP COLUMN expired_at, DROP COLUMN expired_run_id, DROP COLUMN tracking_scope_hash")
    op.execute("ALTER TABLE crawl_state.discovery_targets DROP COLUMN coverage_complete, DROP COLUMN termination_reason")
    op.execute("ALTER TABLE crawl_state.crawl_runs DROP COLUMN phase, DROP COLUMN scope_hash, DROP COLUMN expected_targets, DROP COLUMN coverage_complete, DROP COLUMN cdc_status, DROP COLUMN cdc_reason, DROP COLUMN cdc_finished_at, DROP COLUMN expired_url_count, DROP COLUMN reappeared_url_count")
