"""Track intentional raw removal without deleting analytical data."""
from alembic import op

revision = "0005_raw_cleanup"
down_revision = "0004_location_cities"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("ALTER TABLE crawl_state.jobs ADD COLUMN fetch_retry_base INTEGER NOT NULL DEFAULT 0")
    op.execute("ALTER TABLE crawl_state.raw_objects ADD COLUMN purged_at TIMESTAMPTZ, ADD COLUMN refreshed_at TIMESTAMPTZ")
    op.execute("""CREATE TABLE crawl_state.raw_cleanup_log (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        job_id BIGINT NOT NULL,
        bucket_name TEXT NOT NULL, object_key TEXT NOT NULL,
        object_version TEXT, content_sha256 TEXT NOT NULL,
        bytes BIGINT NOT NULL, reason TEXT NOT NULL,
        status TEXT NOT NULL CHECK (status IN ('pending','deleted','missing','changed')),
        created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
        finished_at TIMESTAMPTZ
    )""")
    op.execute("CREATE INDEX idx_cleanup_job ON crawl_state.raw_cleanup_log(job_id, id)")


def downgrade():
    raise RuntimeError("Raw cleanup migration is forward-only; retain deletion history")
